### ISSUE TITLE
incompatibility with nushell version 0.100.0

### ISSUE THREAD

**Issue by yoacinsoy** [yybit/nu_plugin_compress#1]
Steps to reproduce:

1. Install nushell latest
2. Download and compile the plugin
3. Try to add plugin
4. Get error

Error: nu::shell::plugin_failed_to_load

× Plugin failed to load: Plugin `compress` is compiled for nushell version 0.98.0, which is not compatible with version 0.100.0

![image](https://github.com/user-attachments/assets/f1f5eb54-ed6a-45a5-9646-54a8f5796e9f)

**Comment by yybit** [comment]
Thx, the dependencies have been updated in version 0.2.0, you can give it a try.

**Comment by windtail** [comment]
it's really hard to keep pace with nu, as [v0.101.0](https://www.nushell.sh/blog/2024-12-24-nushell_0_101_0.html) is released ^_^

**Comment by yybit** [comment]
> it's really hard to keep pace with nu, as [v0.101.0](https://www.nushell.sh/blog/2024-12-24-nushell_0_101_0.html) is released ^_^

I'll try to keep up. Version has been updated.
